### ISSUE TITLE
Build failed - flatmap error

### ISSUE THREAD

**Issue by juanmaguerrero** [codrops/3DGridContentPreview#2]
I follow the steps on the readme, but I keep getting build error:

```
➜  3DGridContentPreview git:(main) npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

> @parcel/source-map@2.0.0-alpha.4.21 install /Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/@parcel/source-map
> node-gyp-build


> @parcel/watcher@2.0.0-alpha.10 install /Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/@parcel/watcher
> node-gyp-build


> core-js@3.12.1 postinstall /Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.4.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 1199 packages from 831 contributors and audited 1199 packages in 21.133s
found 73 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
➜  3DGridContentPreview git:(main) npm start

> 3DGridContentPreview@1.0.0 start /Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview
> parcel src/index.html --open

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
TypeError: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
    at Object.run (/Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/@parcel/core/lib/requests/AssetRequest.js:94:122)

```

If someone could point me in the right direction? Thanks so much in advance!

**Comment by Sheshiyer** [comment]
🚨 Build failed.
Error: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
TypeError: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
    at Object.run (/Users/juanmaguerrero/Documents/PROYECTOS/vadkiria/2021-src/3DGridContentPreview/node_modules/@parcel/core/lib/requests/AssetRequest.js:94:122) 

Try git bash and run the commands from readme
